shift_project/project_meta/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^shifts_app/', include('shifts_app.urls', namespace='shifts_app')),
    url(r'^shifts_app/', include('django.contrib.auth.urls')),
]

shift_project/shifts_app/urls.py
from django.conf.urls import url
from . import views 
from django.contrib.auth.views import login

app_name = 'shifts_app'

urlpatterns = [ 

    url(r'^$', views.selection_page, name= 'selection_page'),  
    url(r'^employee_main/$', views.employee_main, name= 'employee_main'),  
    url(r'^sup_main/$',views.sup_main, name='sup_main'), 
    url(r'^login/$', login, {'template_name':'shifts_app/login.html'}), 
    url(r'^add_shifts/$',views.add_shifts, name='add_shifts'),   

    url(r'^monday/$',views.monday, name='monday'), 
    url(r'^tuesday/$',views.tuesday, name='tuesday'),
    url(r'^wednesday/$',views.wednesday, name='wednesday'),
    url(r'^thursday/$',views.thursday, name='thursday'),
    url(r'^friday/$',views.friday, name='friday'),
    url(r'^saturday/$',views.saturday, name='saturday'),
    url(r'^sunday/$',views.sunday, name='sunday'),

    #url(r'^(?P<group_id>[0-9]+)/$',views.index, name='index'),


    url(r'^shift_cover/$',views.shift_cover, name='shift_cover'),
    url(r'^(?P<shift_id>[0-9]+)/$',views.detail, name='detail'),
    
    url(r'shift/(?P<pk>[0-9]+)/delete/$',views.ShiftDelete.as_view(),name='shift-delete'),
    url(r'^chat_room/$',views.chat_room, name='chat_room'),
]

shift_project/shifts_app/forms.py
from django import forms
from .shift import Shift
from .run import Run
from .shift_group import ShiftGroup

class ShiftForm(forms.ModelForm):
    class Meta:
        model = Shift
        fields = ['start_datetime', 'end_datetime', 'shift_cover','user_id','covered']

class RunForm(forms.ModelForm):
    class Meta:
        model = Run
        fields = ['start_datetime', 'end_datetime']

shift_project/shifts_app/views.py
from django.shortcuts import render,get_object_or_404
from django.shortcuts import redirect
from django.http import Http404
from django.views.generic.edit import DeleteView
from django.core.urlresolvers import reverse_lazy
from .shift import Shift
from .run import Run
from .shift_group import ShiftGroup
from django.conf import settings
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test
from shifts_app.forms import ShiftForm
from django.core.urlresolvers import reverse


def check_admin(user):
   return user.is_superuser


def selection_page(request):
    return render(request,'shifts_app/selection_page.html')

@user_passes_test(check_admin)
@login_required(login_url='/shifts_app/login/')
def sup_main(request):
    all_shifts = Shift.objects.all()
    all_runs = Run.objects.all()
    context = {'all_shifts': all_shifts,'all_runs':all_runs}
    return render(request,'shifts_app/sup_main.html', context)


@login_required(login_url='/shifts_app/login/')
def employee_main(request):
    all_shifts = Shift.objects.all()
    all_runs = Run.objects.all()
    
    context = {
        'all_shifts': all_shifts,
        'all_runs':all_runs,
    }
    if not request.user.is_authenticated:
        return redirect('%s?next=%s' % (settings.LOGIN_URL, request.path))
    else:
        return render(request,'shifts_app/employee_main.html', context)

@login_required(login_url='/shifts_app/login/')
def monday(request):
    all_shifts = Shift.objects.all()
    all_runs = Run.objects.all()
    context = {'all_shifts': all_shifts,'all_runs':all_runs}
    return render(request,'shifts_app/monday.html', context)

@login_required(login_url='/shifts_app/login/')
def tuesday(request):
    all_shifts = Shift.objects.all()
    all_runs = Run.objects.all()
    context = {'all_shifts': all_shifts,'all_runs':all_runs}
    return render(request,'shifts_app/tuesday.html', context)

@login_required(login_url='/shifts_app/login/')
def wednesday(request):
    all_shifts = Shift.objects.all()
    all_runs = Run.objects.all()
    context = {'all_shifts': all_shifts,'all_runs':all_runs}
    return render(request,'shifts_app/wednesday.html', context)

@login_required(login_url='/shifts_app/login/')
def thursday(request):
    all_shifts = Shift.objects.all()
    all_runs = Run.objects.all()
    context = {'all_shifts': all_shifts,'all_runs':all_runs}
    return render(request,'shifts_app/thursday.html', context)

@login_required(login_url='/shifts_app/login/')
def friday(request):
    all_shifts = Shift.objects.all()
    all_runs = Run.objects.all()
    context = {'all_shifts': all_shifts,'all_runs':all_runs}
    return render(request,'shifts_app/friday.html', context)

@login_required(login_url='/shifts_app/login/')
def saturday(request):
    all_shifts = Shift.objects.all()
    all_runs = Run.objects.all()
    context = {'all_shifts': all_shifts,'all_runs':all_runs}
    return render(request,'shifts_app/saturday.html', context)

@login_required(login_url='/shifts_app/login/')
def sunday(request):
    all_shifts = Shift.objects.all()
    all_runs = Run.objects.all()
    context = {'all_shifts': all_shifts,'all_runs':all_runs}
    return render(request,'shifts_app/sunday.html', context)


#def index(request,group_id):
    #group = get_object_or_404(ShiftGroup, pk=group_id)
    #return render(request,'shifts_app/index.html', {'group': group})

@login_required(login_url='/shifts_app/login/')
def detail(request,shift_id):
    shift = get_object_or_404(Shift, pk=shift_id)
    return render(request,'shifts_app/detail.html', {'shift': shift})

@login_required(login_url='/shifts_app/login/')
def shift_cover(request):
    
    all_shifts = Shift.objects.all()
    try:
        selected_shift = all_shifts.get(pk=request.POST["shift"])
    except (KeyError, Shift.DoesNotExist):
        return render(request,'shifts_app/shift_cover.html', 
        {
            'all_shifts' : all_shifts,
            'error_message':"no valid Shift selected",
        })
    else:
        selected_shift.shift_cover = True
        selected_shift.covered = True

        selected_shift.save()
        return render(request,'shifts_app/shift_cover.html', {'all_shifts' : all_shifts})


class ShiftDelete(DeleteView):
    model = Shift
    success_url = reverse_lazy('shifts_app:sup_main')


@login_required(login_url='/shifts_app/login/')
def chat_room(request):
    all_shifts = Shift.objects.all()
    all_runs = Run.objects.all()
    context = {'all_shifts': all_shifts,'all_runs':all_runs}
    return render(request,'shifts_app/chat_room.html', context)



@user_passes_test(check_admin)
def add_shifts(request):
    if request.method =='POST':
        form = ShiftForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('shifts_app:sup_main'))
        else :
            return render(request, 'shifts_app/add_shifts.html', {'form': form})
    else:
        form = ShiftForm()

        args = {'form': form}
        return render(request, 'shifts_app/add_shifts.html', args)

shift_project/shifts_app/templates/shifts_app/chat_room.html
{% extends 'shifts_app/base.html'%}

{% block body %}
    {% load staticfiles %}
    <form id="form1">
        Type: <input name="post" type="text">
    </form>
    <button onclick="output()"> Submit </button>

    <script>
        function output() {
            var x,y;
            x = document.getElementById("form1");
            y = x.elements["post"].value;
            document.getElementById("demo").innerHTML = y;
        }
    </script>

    <p id="demo"></p>
    
{% endblock %}

shift_project/shifts_app/templates/shifts_app/employee_main.html
{% extends 'shifts_app/base.html'%}

{% block body %}
    {% load staticfiles %}
    {% if all_shifts %}
    <h3>Here are your current shifts</h3>
    <h3> Shifts:</h3>
        <table class="table table-striped">
                <thead class="thead-dark">
                <tr>
                    
                    <th scope="col">Day</th>
                    <th scope="col">Date</th>
                    <th scope="col">Start Time</th>
                    <th scope="col">End Time</th>
                    <th scope="col">Runs</th>
                    <th scope="col">Cover</th>


                </tr>
                </thead>
                <tbody>
                {% for shift in all_shifts %}
                {% if user.get_username == shift.user_id %}
                <tr>
                    <td >{{shift.start_datetime|date:"l"}}</td>
                    <td>{{shift.start_datetime|date:"M d"}}</td>
                    <td>{{shift.start_datetime|time:"H:i:s"}}</td>
                    <td>{{shift.end_datetime|time:"H:i:s"}}</td>
                    <td><a class="btn btn-danger" href="{% url 'shifts_app:detail' shift.id %}" role="button">Runs</a></td>
                    <td>
                        <form action="{% url 'shifts_app:shift_cover' %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="shift" id ="shift{{ forloop.counter }}" value="{{ shift.id }}">
                            <input type="submit" value="submit" >
                            
                        </form>
                    </td>
                    
                </tr>
                {% endif %}
                {% endfor %}
                
                </tbody>
            </table>
    {% else %}
        <h3>You have no Shifts</h3>
    {% endif %}
{% endblock %}

shift_project/shifts_app/templates/shifts_app/friday.html
{% extends 'shifts_app/base.html'%}

{% block body %}
    {% load staticfiles %}
    <table class="table table-striped">
            <thead class="thead-dark">
            <tr>
                
                <th scope="col">Day</th>
                <th scope="col">Date</th>
                <th scope="col">Start Time</th>
                <th scope="col">End Time</th>
                <th scope="col">Runs</th>

            </tr>
            </thead>
            <tbody>
            {% for shift in all_shifts %}
                {% if user.get_username == shift.user_id %}
                {% if shift.start_datetime|date:"l" = 'Friday' %}
                <tr>
                    <td >{{shift.start_datetime|date:"l"}}</td>
                    <td>{{shift.start_datetime|date:"M d"}}</td>
                    <td>{{shift.start_datetime|time:"H:i:s"}}</td>
                    <td>{{shift.end_datetime|time:"H:i:s"}}</td>
                    <td><a class="btn btn-danger" href="{% url 'shifts_app:detail' shift.id %}" role="button">Runs</a></td>
                </tr>
                {% endif %}
                {% endif %}
            {% endfor %}
            
            </tbody>
        </table>
{% endblock %}

shift_project/shifts_app/templates/shifts_app/index.html
{% extends 'shifts_app/base.html'%}

{% block body %}
    {% load staticfiles %}
        <h3>Here are your shifts: </h3>
        <ul style="list-style-type:none">
            {% for shift in group.shifts_related.all %}
                <li><a href="{% url 'shifts_app:detail' group.id shift.id %}">{{shift.start_datetime|date:"M d, Y"}} {{shift.start_datetime|time:"H:i:s"}} - {{shift.end_datetime|date:"M d, Y"}} {{shift.end_datetime|time:"H:i:s"}}</a></li>
            {% endfor %}
        </ul>
{% endblock %}

shift_project/shifts_app/templates/shifts_app/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}UNIshifts{% endblock %}</title>
    {% load url from future %}
    {% load staticfiles %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'shifts_app/style.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Exo+2:500" rel="stylesheet" type="text/css">

    <nav class= "navbar navbar-inverse">
        <div class= "container-fluid">
            <div class= "navbar-header">
                <a class="navbar-brand" href="{% url 'shifts_app:selection_page' %}">UNI.</a>
            </div>
        </div>
    </nav>
</head>



<body>
    <div class="container">
        <h1>Welcome</h1>
        <p>
            You can log in here!
        </p>
        <h2>Login</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Login</button>
        </form>
    </div>
</body>

shift_project/shifts_app/templates/shifts_app/monday.html
{% extends 'shifts_app/base.html'%}

{% block body %}
    {% load staticfiles %}
        
        <table class="table table-striped">
                <thead class="thead-dark">
                <tr>
                    
                    <th scope="col">Day</th>
                    <th scope="col">Date</th>
                    <th scope="col">Start Time</th>
                    <th scope="col">End Time</th>
                    <th scope="col">Runs</th>

                </tr>
                </thead>
                <tbody>
                {% for shift in all_shifts %}
                    {% if user.get_username == shift.user_id %}
                    {% if shift.start_datetime|date:"l" = 'Monday' %}
                    <tr>
                        <td >{{shift.start_datetime|date:"l"}}</td>
                        <td>{{shift.start_datetime|date:"M d"}}</td>
                        <td>{{shift.start_datetime|time:"H:i:s"}}</td>
                        <td>{{shift.end_datetime|time:"H:i:s"}}</td>
                        <td><a class="btn btn-danger" href="{% url 'shifts_app:detail' shift.id %}" role="button">Runs</a></td>
                    </tr>
                    {% endif %}
                    {% endif %}
                {% endfor %}
                
                </tbody>
            </table>

{% endblock %}

shift_project/shifts_app/templates/shifts_app/saturday.html
{% extends 'shifts_app/base.html'%}

{% block body %}
    {% load staticfiles %}
    <table class="table table-striped">
            <thead class="thead-dark">
            <tr>
                
                <th scope="col">Day</th>
                <th scope="col">Date</th>
                <th scope="col">Start Time</th>
                <th scope="col">End Time</th>
                <th scope="col">Runs</th>

            </tr>
            </thead>
            <tbody>
            {% for shift in all_shifts %}
                {% if user.get_username == shift.user_id %}
                {% if shift.start_datetime|date:"l" = 'Saturday' %}
                <tr>
                    <td >{{shift.start_datetime|date:"l"}}</td>
                    <td>{{shift.start_datetime|date:"M d"}}</td>
                    <td>{{shift.start_datetime|time:"H:i:s"}}</td>
                    <td>{{shift.end_datetime|time:"H:i:s"}}</td>
                    <td><a class="btn btn-danger" href="{% url 'shifts_app:detail' shift.id %}" role="button">Runs</a></td>
                </tr>
                {% endif %}
                {% endif %}
            {% endfor %}
            
            </tbody>
        </table>
{% endblock %}

shift_project/shifts_app/templates/shifts_app/selection_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}UNIshifts{% endblock %}</title>
    {% load url from future %}
    {% load staticfiles %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'shifts_app/style.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Exo+2:500" rel="stylesheet" type="text/css">

    <nav class= "navbar navbar-inverse">
        <div class= "container-fluid">
            <div class= "navbar-header">
                <a class="navbar-brand" href="{% url 'shifts_app:selection_page' %}">UNI.</a>
            </div>
        </div>
    </nav>
</head>






<a class="btn btn-danger" href="{% url 'shifts_app:employee_main' %}" role="button"  style="height:300px;width:718px","font-size : 200px">Employee </a>


<a class="btn btn-danger" href="{% url 'shifts_app:sup_main' %}" role="button" style="height:300px;width:717px">Supervisor</a>

shift_project/shifts_app/templates/shifts_app/shift_cover.html
{% extends 'shifts_app/base.html'%}

{% block body %}
    <h1>Shifts to be Covered</h1>

    {% load staticfiles %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'shifts_app/style.css' %}" />
    <table class="table table-striped">
            <thead class="thead-dark">
            <tr>
                
                <th scope="col">Day</th>
                <th scope="col">Date</th>
                <th scope="col">Start Time</th>
                <th scope="col">End Time</th>
                <th scope="col">User ID</th>
                <th scope="col">Picked Up</th>
                
                

            </tr>
            </thead>
            <tbody>
            {% for shift in all_shifts %}
                {% if shift.shift_cover %}
                    <tr>
                        <td >{{shift.start_datetime|date:"l"}}</td>
                        <td>{{shift.start_datetime|date:"M d"}}</td>
                        <td><b>{{shift.start_datetime|time:"H:i:s"}}</b></td>
                        <td><b>{{shift.end_datetime|time:"H:i:s"}}</b></td>
                        <td>{{ shift.user_id }}</td>
                        <td>
                            <form action="{% url 'shifts_app:shift_cover' %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" name="shift" id ="shift{{ forloop.counter }}" value="{{ shift.id }}">
                                {% if shift.covered %}
                                    <img src="https://i.imgur.com/b9b13Rd.png">
                                {% endif %}
                                <input type="submit" value="submit" >          
                            </form>



                        </td>

                    </tr>
                {% endif %}
            {% endfor %}
            
            </tbody>
        </table>


{% endblock %}

shift_project/shifts_app/templates/shifts_app/sunday.html
{% extends 'shifts_app/base.html'%}

{% block body %}
    {% load staticfiles %}
    <table class="table table-striped">
            <thead class="thead-dark">
            <tr>
                
                <th scope="col">Day</th>
                <th scope="col">Date</th>
                <th scope="col">Start Time</th>
                <th scope="col">End Time</th>
                <th scope="col">Runs</th>

            </tr>
            </thead>
            <tbody>
            {% for shift in all_shifts %}
                {% if user.get_username == shift.user_id %}
                {% if shift.start_datetime|date:"l" = 'Sunday' %}
                <tr>
                    <td >{{shift.start_datetime|date:"l"}}</td>
                    <td>{{shift.start_datetime|date:"M d"}}</td>
                    <td>{{shift.start_datetime|time:"H:i:s"}}</td>
                    <td>{{shift.end_datetime|time:"H:i:s"}}</td>
                    <td><a class="btn btn-danger" href="{% url 'shifts_app:detail' shift.id %}" role="button">Runs</a></td>
                </tr>
                {% endif %}
                {% endif %}
            {% endfor %}
            
            </tbody>
        </table>
{% endblock %}

shift_project/shifts_app/templates/shifts_app/sup_main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}UNIshifts{% endblock %}</title>
    {% load url from future %}
    {% load staticfiles %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'shifts_app/style.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Exo+2:500" rel="stylesheet" type="text/css">

    <nav class= "navbar navbar-inverse">
        <div class= "container-fluid">
            <div class= "navbar-header">
                <a class="navbar-brand" href="{% url 'shifts_app:sup_main' %}">{{ user.get_username }}</a>
            </div>
            <div class="nav-item">
                <a class="nav-link" href="{% url 'shifts_app:sup_main' %}">All Shifts</a>
            </div>
            <div class="nav-item">
                <a class="nav-link" href="{% url 'shifts_app:add_shifts' %}">Add Shifts</a>
            </div>
            <div class="nav-item">
                <a href="{% url 'logout' %}?next=/shifts_app/">Logout</a>
            </div>
        </div>
    </nav>
</head>

<body>
        <table class="table table-striped">
                <thead class="thead-dark">
                <tr>
                    <th scope="col">Driver</th>
                    <th scope="col">Day</th>
                    <th scope="col">Date</th>
                    <th scope="col">Start Time</th>
                    <th scope="col">End Time</th>
                    <th scope="col">Runs</th>
                    <th scope="col">Delete</th>
    
                </tr>
                </thead>
                <tbody>
                {% for shift in all_shifts %}
                    <tr>
                        <td >{{shift.user_id}}</td>
                        <td >{{shift.start_datetime|date:"l"}}</td>
                        <td>{{shift.start_datetime|date:"M d"}}</td>
                        <td>{{shift.start_datetime|time:"H:i:s"}}</td>
                        <td>{{shift.end_datetime|time:"H:i:s"}}</td>
                        <td><a class="btn btn-danger" href="{% url 'shifts_app:detail' shift.id %}" role="button">Runs</a></td>
                        <td>
                            <form action="{% url 'shifts_app:shift-delete' shift.id %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" name="shift" id ="shift{{ forloop.counter }}" value="{{ shift.id }}">
                                <input type="submit" value="Remove" > 
                            </form>
                        </td>

                    </tr>

                {% endfor %}
                
                </tbody>
            </table>
</body>


</html>

shift_project/shifts_app/templates/shifts_app/thursday.html
{% extends 'shifts_app/base.html'%}

{% block body %}
    {% load staticfiles %}
    <table class="table table-striped">
            <thead class="thead-dark">
            <tr>
                
                <th scope="col">Day</th>
                <th scope="col">Date</th>
                <th scope="col">Start Time</th>
                <th scope="col">End Time</th>
                <th scope="col">Runs</th>

            </tr>
            </thead>
            <tbody>
            {% for shift in all_shifts %}
                {% if user.get_username == shift.user_id %}
                {% if shift.start_datetime|date:"l" = 'Thursday' %}
                <tr>
                    <td >{{shift.start_datetime|date:"l"}}</td>
                    <td>{{shift.start_datetime|date:"M d"}}</td>
                    <td>{{shift.start_datetime|time:"H:i:s"}}</td>
                    <td>{{shift.end_datetime|time:"H:i:s"}}</td>
                    <td><a class="btn btn-danger" href="{% url 'shifts_app:detail' shift.id %}" role="button">Runs</a></td>
                </tr>
                {% endif %}
                {% endif %}
            {% endfor %}
            
            </tbody>
        </table>
{% endblock %}

shift_project/shifts_app/templates/shifts_app/tuesday.html
{% extends 'shifts_app/base.html'%}

{% block body %}
    {% load staticfiles %}
    <table class="table table-striped">
            <thead class="thead-dark">
            <tr>
                
                <th scope="col">Day</th>
                <th scope="col">Date</th>
                <th scope="col">Start Time</th>
                <th scope="col">End Time</th>
                <th scope="col">Runs</th>

            </tr>
            </thead>
            <tbody>
            {% for shift in all_shifts %}
                {% if user.get_username == shift.user_id %}
                {% if shift.start_datetime|date:"l" = 'Tuesday' %}
                <tr>
                    <td >{{shift.start_datetime|date:"l"}}</td>
                    <td>{{shift.start_datetime|date:"M d"}}</td>
                    <td>{{shift.start_datetime|time:"H:i:s"}}</td>
                    <td>{{shift.end_datetime|time:"H:i:s"}}</td>
                    <td><a class="btn btn-danger" href="{% url 'shifts_app:detail' shift.id %}" role="button">Runs</a></td>
                </tr>
                {% endif %}
                {% endif %}
            {% endfor %}
            
            </tbody>
        </table>
{% endblock %}

shift_project/shifts_app/templates/shifts_app/wednesday.html
{% extends 'shifts_app/base.html'%}

{% block body %}
    {% load staticfiles %}
    <table class="table table-striped">
            <thead class="thead-dark">
            <tr>
                
                <th scope="col">Day</th>
                <th scope="col">Date</th>
                <th scope="col">Start Time</th>
                <th scope="col">End Time</th>
                <th scope="col">Runs</th>

            </tr>
            </thead>
            <tbody>
            {% for shift in all_shifts %}
                {% if user.get_username == shift.user_id %}
                {% if shift.start_datetime|date:"l" = 'Wednesday' %}
                <tr>
                    <td >{{shift.start_datetime|date:"l"}}</td>
                    <td>{{shift.start_datetime|date:"M d"}}</td>
                    <td>{{shift.start_datetime|time:"H:i:s"}}</td>
                    <td>{{shift.end_datetime|time:"H:i:s"}}</td>
                    <td><a class="btn btn-danger" href="{% url 'shifts_app:detail' shift.id %}" role="button">Runs</a></td>
                </tr>
                {% endif %}
                {% endif %}
            {% endfor %}
            
            </tbody>
        </table>
{% endblock %}